---
language: php

os: [ linux ]
dist: bionic

version: ~> 1.0

php: "7.3"

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$HOME/.rvm"
    - "${TMPDIR:-/tmp}/phpstan/cache"

branches:
  only:
    - master
    - develop
    - wip

env:
  global:
    - ORCA_SUT_NAME=drupal/example
    - ORCA_SUT_BRANCH=master
    - ORCA_PACKAGES_CONFIG=example/tests/packages.yml
    - ORCA_PACKAGES_CONFIG_ALTER=example/tests/packages_alter.yml
    - ORCA_SUT_DIR=${TRAVIS_BUILD_DIR}/../example
    - ORCA_SELF_TEST_COVERAGE_CLOVER=$HOME/build/logs/clover-self.xml

jobs:
  fast_finish: true
  include:
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan", env: ORCA_JOB=DEPRECATED_CODE_SCAN }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Isolated test w/ recommended package versions and code coverage", env: ORCA_JOB=ISOLATED_RECOMMENDED ORCA_COVERALLS_ENABLE=TRUE }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions & previous minor release of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Integrated test w/ dev package versions & next minor dev version of Drupal core", env: ORCA_JOB=CORE_NEXT ORCA_ENABLE_NIGHTWATCH=FALSE }
    - { name: "D9 readiness test", php: "7.3", env: ORCA_JOB=D9_READINESS }
    - { name: "Custom job", env: ORCA_JOB=CUSTOM ORCA_CUSTOM_FIXTURE_INIT_ARGS="--help" ORCA_CUSTOM_TESTS_RUN_ARGS="--help" }
    - { name: "Integrated live test", env: ORCA_JOB=LIVE_TEST ORCA_ENABLE_NIGHTWATCH=FALSE }
  allow_failures:
    - env: ORCA_JOB=LIVE_TEST ORCA_ENABLE_NIGHTWATCH=FALSE

before_install:
  - nvm use 12.13.1
  - composer self-update 1.10.16
  - ../orca/bin/travis/self-test/before_install.sh
  - ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/self-test/install.sh
  - ../orca/bin/travis/install.sh

before_script: ../orca/bin/travis/before_script.sh

script:
  - ../orca/bin/travis/self-test/script.sh
  - ../orca/bin/travis/script.sh

after_script:
  - ../orca/bin/travis/before_cache.sh
  - ../orca/bin/travis/self-test/after_success.sh
  - unset ORCA_COVERAGE_ENABLE
  - unset ORCA_COVERALLS_ENABLE
  - ../orca/bin/travis/after_success.sh
  - ../orca/bin/travis/after_failure.sh
  - ../orca/bin/travis/after_script.sh

notifications:
  slack:
    rooms:
      - secure: O5nsfr16x9YR1zXjc9PW7Nd9Cfe9M9FeG2EA7i8+OwwyLvx2q18ex/iYWYmA/ixSa8sq+VczujoLjx8Q+HyuB+lrvZ5pZvVeoGhF2Mf1cbZp/qRuuHf8y7R1qW3IUQi8eTNnXSwxLo7+SmdV34qduPsZkxs/nRQGdBHcsZdcYytUAkDYfTJVZEix4qZ9nEufBSjN3UGTL/h8F4sBnHOi2uVnh358wDA8jlpedrM6cnQquwEEA9nb7ICABt5LQUiZeE/ebXLN0lF+nEMG1ANcEOonUSrGFrcS4HqC8sGVruUOqMcxrD/ku1+glBfj5gRW9FV0fK+41aaMgvlOfdQzfvPuYO08dHkip3Dc6nc7cRb3S7yvOMLoGtSH+r8ImfaKffqIozNAE0oyzEL0oyKtPtHEbGgm1bV77qqFkbSunf8Hs//7L5CowOUqef/Z+9gFH4zySsZiP/iQ6Cnts6MmoSdog276/AbIGwuTrmNCcI6Ow5ZeT/CW3vSJ/5wA4vbrrFBYTLJS9BQ2waT1LwTll1lYMe0XS5LMTbycyceTj8BQl3yswwbm3pS7IUg/feO5TDOqYvckvqXnshbPrQuAz5Pk7yGoUTT2TMSYovd1+RelPdYXGgI9+YSHRDWd+56i75BMIYD40+vfLpZosBvIEYQjpH1UO1Hb3MJ1sjSnkQs= #orca-status
    on_success: change
    on_failure: change
    if: branch = master
