---
language: php

php: 7.1

addons:
  chrome: stable

cache:
  directories:
    - "$HOME/.composer/cache"
    - "$HOME/.drush/cache"
    - "$TMPDIR/phpstan/cache"

branches:
  only:
    - master
    - develop
    - wip

env:
  global:
    - ORCA_SUT_NAME=drupal/example
    - ORCA_SUT_BRANCH=master
    - ORCA_PACKAGES_CONFIG=tests/Fixture/packages.yml
    - ORCA_PACKAGES_CONFIG_ALTER=example/tests/packages_alter.yml

matrix:
  fast_finish: true
  include:
    - { name: "Static code analysis", env: ORCA_JOB=STATIC_CODE_ANALYSIS }
    - { name: "Deprecated code scan w/ SUT", env: ORCA_JOB=DEPRECATED_CODE_SCAN_SUT }
    - { name: "Deprecated code scan w/ dependencies", env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB }
    - { name: "Isolated test w/ recommended package versions", env: ORCA_JOB=ISOLATED_RECOMMENDED }
    - { name: "Integrated test w/ recommended package versions", env: ORCA_JOB=INTEGRATED_RECOMMENDED }
    - { name: "Previous minor version of Drupal core", env: ORCA_JOB=CORE_PREVIOUS }
    - { name: "Isolated test w/ dev package versions", env: ORCA_JOB=ISOLATED_DEV }
    - { name: "Integrated test w/ dev package versions", env: ORCA_JOB=INTEGRATED_DEV }
    - { name: "Next pre-release of Drupal core", env: ORCA_JOB=CORE_NEXT }
  allow_failures:
    - env: ORCA_JOB=DEPRECATED_CODE_SCAN_CONTRIB

before_install: ../orca/bin/travis/before_install.sh

install:
  - ../orca/bin/travis/self-test/install.sh
  - ../orca/bin/travis/install.sh

script:
  - ../orca/bin/travis/self-test/script.sh
  - ../orca/bin/travis/script.sh
  - ../orca/bin/travis/after_failure.sh
