---
acquia/acsf-tools:
  version: "*"
  dir: acsf-tools
  module: false

acquia/drupal-spec-tool:
  version: "*"
  dir: drupal-spec-tool
  module: false

drupal/acquia_commercemanager:
  version: "*"
  dir: commerce-manager
  module: acm
  submodules:
    # - acm_cart
    - acm_checkout
    # - acm_customer
    - acm_diagnostic
    # - acm_exception
    # - acm_payment
    # - acm_product
    # - acm_promotion
    # - acm_sku
    # - acm_sku_position
    # @todo Temporary workaround.
    - pcb

drupal/acquia_connector:
  version: "*"
  dir: acquia-connector
  module: acquia_connector
  submodules: []
    # - acquia_search

drupal/acquia_contenthub:
  version: "~1.0"
  dir: content-hub-d8
  module: acquia_contenthub
  submodules:
    - acquia_contenthub_diagnostic
    - acquia_contenthub_status
    - acquia_contenthub_subscriber

drupal/acquia_lift:
  version: "*"
  dir: acquia_lift
  module: acquia_lift
  submodules:
    - acquia_lift_inspector

drupal/acquia_purge:
  version: "*"
  dir: acquia_purge
  module: acquia_purge

drupal/acsf:
  version: "*"
  dir: acsf
  module: acsf
  submodules:
    - acsf_duplication
    - acsf_sso
    - acsf_theme
    - acsf_variables

drupal/lightning_api:
  version: "*"
  dir: lightning-api
  module: lightning_api

drupal/lightning_core:
  version: "*"
  dir: lightning-core
  module: lightning_core
  submodules:
    - lightning_contact_form
    - lightning_page
    - lightning_roles
    - lightning_search

drupal/lightning_layout:
  version: "*"
  dir: lightning-layout
  module: lightning_layout
  submodules:
    - lightning_landing_page

drupal/lightning_media:
  version: "*"
  dir: lightning-media
  module: lightning_media
  submodules:
    - lightning_media_audio
    - lightning_media_bulk_upload
    - lightning_media_document
    - lightning_media_image
    - lightning_media_instagram
    - lightning_media_slideshow
    - lightning_media_twitter
    - lightning_media_video

drupal/lightning_workflow:
  version: "*"
  dir: lightning-workflow
  module: lightning_workflow
  submodules:
    - lightning_scheduler

drupal/media_acquiadam:
  version: "*"
  dir: media_acquiadam
  # module: media_acquiadam
  submodules:
    - lightning_acquiadam
    # - media_acquiadam_example
    - media_acquiadam_report
